name = "nftdiplom/diplom"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'nftdiplom/diplom'"

[repository]
user = "nftdiplom"
project = "diplom"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"
